const express=require('express')
const bodyParser=require('body-parser')
const Sequelize=require('./util/database')
const enter=require('./routes/enter')
const expense=require('./routes/expense')
const User=require('./model/user')
const Expense=require('./model/expense')
const cors=require('cors')
const app=express()
app.use(cors())
app.use(bodyParser.json({extended:false}))
app.use('/user',enter)
app.use('/expense',expense)
User.hasMany(Expense)
Expense.belongsTo(User)
Sequelize
.sync()
.then(()=>{
    app.listen(4000)
})
.catch(err=>{
    console.log(err)
})